os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - eval "$(curl -sL swift.qutheory.io/travis)"
script:
  - swift build
  - swift test
notifications:
  email:
    on_success: never
    on_failure: change



